#!/usr/bin/ruby
require 'tmpdir'
require 'fileutils'

args = ARGV.map {|a| a =~ /\ / ? '"' + a + '"' : a}.join ' '
macos_version = `/usr/bin/sw_vers -productVersion`.strip
ruby = RbConfig.ruby
system_ruby = ruby.start_with? '/System'

# Fix for broken 10.14 Ruby
if macos_version == '10.14' && system_ruby
  dir = Dir.mktmpdir("bridgesupport-ruby")
  FileUtils.cp(ruby, dir)
  ruby = "#{dir}/#{File.basename ruby}"
end

exec "#{ruby} #{args}"

